@startuml classes
left to right direction
skinparam actorStyle Awesome
skinparam ArrowThickness 1
!theme aws-orange
skinparam backgroundcolor White

'Titre'
title Classes

'Comment'
class Comment {
    {static} +id: int
    +creation_date: date
    +content: longtext
}

'Trick Group'
class Trick_Group {
    {static} +id: int
    +name: string
}

'Member'
class Member {
    {static} +id: int
    +first_name: string
    +last_name: string
}

'Login Credentials'
class LoginCredentials {
    {static} +id: int
    +email: string
    +roles: longtext
    +password: string
    +token: string
    +username: string
    +is_active: boolean
}

'Trick'
class Trick {
    {static} +id: int
    +name: string
    +description: longtext
}

'Hash'
class Hash {
    {static} +id: int
    +hash: string
    +is_active: bool 
}

'Illustration'
class Illustration {
    {static} +id: int
    +type: string
    +path: string 
}

'Avatar'
class Avatar {
    {static} +id: int
    +path: string
}

'Déroulement'
Avatar "1" - "1" Member: $warning("OWN")
LoginCredentials "1" -- "1" Member: $warning("CONNECT")
Hash "1..*" -- "1" Member: $warning("SECURE")
Member "1" -- "*" Trick: $warning("WRITE")
Member "1" -- "*" Comment: $warning("LEAVE")
Trick "1" -- "*" Comment: $warning("CONTAIN")
Trick_Group "1" -- "*" Trick: $warning("HAVE")
Trick "1" -- "*" Illustration: $warning("ILLUSTRATE")
@enduml